echo compile...
g++ -Wall -Wpedantic -Wextra -c main.cpp -o build/main.o
echo link...
g++ build/main.o -o build/piano -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
echo run...
./build/piano
